config/routes.rb
#require 'subdomain'
Ddmap::Application.routes.draw do
  devise_for :users
  get 'job_viewer' => 'job_viewer#index', :as => :job_viewer
  resources :fishing_areas
  resources :staging_areas
  resources :custom_fields
  get 'staging_areas_company/:id.:format' => 'staging_areas#index' # :as => :staging_areas
  get 'marker/:name/:id.:format' => 'markers#show', :as => :markers
  get 'search/:controller/:name/:id.:format' => 'controller#search', :as => :search, :name => :name
  get 'wrrl_company_search/:id.:format' => 'wrrls#company_search', :as => :wrrl_company_search
  get 'wrrl_equipment_type_search/:id.:format' => 'wrrls#equipment_type_search', :as => :wrrls_search
  resources :staging_area_companies
  resources :staging_area_assets
  resources :public_maps
  resources :grp_plans
  resources :grp_areas
  resources :grps
  resources :grp_booms
  resources :grp_boom_types
  resources :devices
  post 'update_locations/:id' => 'devices#update_locations', :as => :update_devices
  resources :layers
  resources :stored_files
  resources :kmls
  resources :points
  resources :fishing_areas
  resources :area_categories

  #post 'ais_feeds/ais1' => 'aisFeeds#ais1'

  post '/public_maps/activate/:id' => 'public_maps#activate'

  resources :licenses
  resources :ships
  resources :fishing_vessels
  resources :fishing_trips
  resources :fishermen
  resources :privileges
  resources :faria_feeds
  resources :staging_area_feeds
  resources :clients
  resources :assets
  #resources :public_ships
  get 'my_ships.:format' => 'ships#index', :distill => 'my' #, :as => :my_ships, 
  get 'shared_ships.:format' => 'ships#index', :distill => 'shared' #, :as => :shared_ships, 
  get 'public_ships.:format' => 'ships#index', :distill => 'public' #, :as => :public_ships, 
  get 'my_ships/:id.:format' => 'assets#show' #, :as => :my_ships
  get 'shared_ships/:id.:format' => 'assets#show' #, :as => :shared_ships
  get 'public_ships/:id.:format' => 'assets#show' #, :as => :public_ships
  #get 'my_items.:format' => 'others#index', :as => :my_items, :distill => 'my'
  # get 'shared_items.:format' => 'others#index', :as => :shared_items, :distill => 'shared'
  # get 'public_items.:format' => 'others#index', :as => :public_items, :distill => 'public'
  # #get 'my_items/:id.:format' => 'assets#show', :as => :my_items
  # get 'shared_items/:id.:format' => 'assets#show', :as => :shared_items
  # get 'public_items/:id.:format' => 'assets#show', :as => :public_items
  resources :maps

  # get '/:controller(/:action(/:id))'
  #
  # post '/:controller(/:action(/:id))'


  #post '/ais_feeds/ais5', to: 'AisFeeds#ais5'

  post '/license/activate' => 'licenses#activate'

  root 'public#index'
  get '/' => 'public#index'

  %w(about products services contact success ).each do |page|
    get "/#{page}" => 'public#show', :page => page
  end
  get ':page' => 'private#show', :as => :private, :page => /map|help|admin/

end

app/models/device.rb
# == Schema Information
# Schema version: 20100505140900
#
# Table name: devices
#
#  id             :integer         not null, primary key
#  created_at     :datetime
#  updated_at     :datetime
#  client_id      :integer
#  device_type_id :integer
#  request_key    :string(255)
#  serial_number  :string(255)
#  common_name    :string(255)
#  is_active      :boolean         default(TRUE)
#

class Device < ActiveRecord::Base
  belongs_to :client
  belongs_to :device_type

  has_one :current_location, :dependent => :destroy  

  has_many :assets, :through => :tethers
  has_many :tethers, :dependent => :destroy

  # validates_uniqueness_of :serial_number, :scope => :device_type_id, :unless => :is_unclaimed?, :message => 'is already in use.'

  def is_unclaimed?
    # A device with no client (like AIS ship).
    self.client_id.nil?
  end

  def update_location
    details = case device_type.name
      when 'spot'  then get_spot_location
      when 'phone' then get_instamapper_location
    end
    unless details.nil?
      current_location = CurrentLocation.find_or_create_by_device_id(id)
      current_location.update_attributes(details)
      assets.each {|a|
        a.update_attribute(:current_location_id, current_location.to_param)
      }
    end
  end

  private
  require 'net/http'
  require 'nokogiri'

  def get_instamapper_location
    # note: for now, we just get the latest position since we're not storing history.
    # see http://www.instamapper.com/fe?page=api for more info on the Instamapper API
    # raise "www.instamapper.com/api?action=getPositions&key=#{request_key}&format=json"
    begin
      json = Net::HTTP.get('www.instamapper.com', "api?action=getPositions&key=#{request_key}&format=json")
    rescue Exception
      Rails.logger.error 'Device.get_instamapper_location ' + $!.inspect, $@
      return
    end
    Rails.logger.info "Instamapper get key=#{request_key}"
    return if json.nil?
    begin
      data = JSON.parse(json)['positions'][0]
      details = {
        :lat => data['latitude'],
        :lon => data['longitude'],
        :timestamp => Time.zone.at(data['timestamp'])
      }
    rescue JSON::ParserError
      Rails.logger.error 'Device.get_instamapper_location: could not parse json:'
    end
    details
  end

  def get_spot_location
    begin
      xml = Net::HTTP.get('share.findmespot.com', "/messageService/guestlinkservlet?glId=#{request_key}&completeXml=true")
    rescue Exception
      Rails.logger.error 'Device.get_spot_location ' + $!.inspect, $@
      return
    end
    Rails.logger.info "Spot get glId=#{request_key}"
    doc = Nokogiri::XML(xml) { |config| config.strict.noblanks }
    return if doc.nil?
    node = doc.css('message')
    return if node.nil? || node.empty?
    node = node.first
    {:lat =>  node.css('latitude').text, :lon => node.css('longitude').text, :timestamp => DateTime.parse(node.css('timestamp').text)}
  end

end

app/models/device_type.rb
# == Schema Information
# Schema version: 20100727173851
#
# Table name: device_types
#
#  id          :integer         primary key
#  name        :string(255)     not null
#  title       :string(255)
#  description :text
#

class DeviceType < ActiveRecord::Base
  has_many :devices
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  layout "private"
  before_filter :ensure_login, :except => [:update_locations]

  def update_locations
    interval = params[:id]
    target = case interval
      when '1' then 'phone'
      when '5' then 'spot'
    end
    DeviceType.find_by_name(target).devices.each do |d|
      #d.send_later(:update_location) if d.assets.any? {|a| a.is_active}
      d.update_location if d.assets.any? {|a| a.is_active}
    end
    render :text => 'OK'
  end

  # GET /devices
  def index
    if @loggedin_user.super?
      # RAILS 3 @devices = Device.find(:all, :conditions => ['client_id IS NOT NULL'] )
      @devices = Device.where('client_id IS NOT NULL')
    elsif @loggedin_user.admin?
      # Can only list devices with the same client
      @devices = Device.where(:client_id, @loggedin_user.client_id)
    else
      # standard users can't view devices list
      error_404
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /devices/new
  # GET /devices/new.xml
  def new
    @device_types = DeviceType.all
    if @loggedin_user.super?
      @clients = Client.all
    end
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.xml
  def create

    # @device = Device.find_or_initialize_by_serial_number(params[:device])
    @device = Device.new(params[:device])

    if params[:client_id].nil?
      @client = @loggedin_user.client
    else
      @client = Client.find(params[:client_id])
    end

    @device.client_id = @client.id

    respond_to do |format|
      format.html {
        if @device.save
          flash[:notice] = 'Device was successfully created.'
          redirect_to(:devices)
          else
          flash[:notice] = 'Error creating device.'
          redirect_to(:back)
        end
      }

      format.js {
        if @device.save
          @device = Device.new
          @device_types = DeviceType.all
          @asset = Asset.find(params[:device][:asset_ids])
        end
        render :partial => 'assets/devices',
                :locals  => {:client => @client,
                             :device => @device,
                             :asset => @asset}
      }
    end
  end

  # PUT /devices/1
  # PUT /devices/1.xml
    def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        flash[:notice] = 'Device was successfully updated.'
        format.html { redirect_to :back }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.xml
  def destroy
    @device = Device.find(params[:id])
    if @device.destroy
      flash[:notice] = 'Device was deleted.'

    respond_to do |format|
      format.html { redirect_to :back }
      format.js {render :partial => 'assets/devices',
                        :locals  => {:client => @client,
                                     :device => @device}
                 }
      end
    end
  end
    
  

  def show
    
  end

end

app/helpers/devices_helper.rb
module DevicesHelper


end

app/views/devices/_ais.html.erb
Please enter the following information for your ship.

<p>
  <%= f.label " mmsi" %><br />
  <%= f.text_field :serial_number, class: "form-control" %>
</p>

<p>
  <%= f.label "Lloyds Number" %><br />
  <%= f.text_field :request_key, class: "form-control" %>
</p>

app/views/devices/_phone.html.erb
To activate tracking of your GPS enabled cell phone, enter the Instamapper API key here. If you have a common name
for the phone, e.g. "Phone #5" you may optionally enter it here.

<p>
  <%= f.label "Name" %><br />
  <%= f.text_field :common_name, class: "form-control" %>
</p>

<p>
  <%= f.label "Instamapper API Key" %><br />
  <%= f.text_field :request_key, class: "form-control" %>
</p>

app/views/devices/_seatrack.html.erb
Please enter your Guardian Mobility Seatrack unit serial number (example: 0403A00010). If you have a common name
for the device, e.g. "Unit #5" you may optionally enter it here.

<p>
  <%= f.label "Name" %><br />
  <%= f.text_field :common_name, class: "form-control" %>
</p>

<p>
  <%= f.label "Serial number" %><br />
  <%= f.text_field :serial_number, class: "form-control" %>
</p>

app/views/devices/_skytrack.html.erb
Please enter your Guardian Mobility Skytrack unit serial number (example: 0403A00010). If you have a common name
for the device, e.g. "Unit #5" you may optionally enter it here.

<p>
  <%= f.label "Name" %><br />
  <%= f.text_field :common_name, class: "form-control" %>
</p>

<p>
  <%= f.label "Serial number" %><br />
  <%= f.text_field :serial_number, class: "form-control" %>
</p>

app/views/devices/_spot.html.erb
 Please enter your Spot unit serial number (example: 009009230) and the 
 request key (example: 0E7i9Dh561CkuhBHp9OufARgLcAzXrPVy) used to retrieve current location data.
 <br /><br />
 The name field is optional if you have a common name
 for the device, e.g. "SPOT #5"

<p>
  <%= f.label "Name" %><br />
  <%= f.text_field :common_name, class: "form-control" %>
</p>

<p>
  <%= f.label "Serial number" %><br />
  <%= f.text_field :serial_number, class: "form-control" %>
</p>

<p>
  <%= f.label "Request key" %><br />
  <%= f.text_field :request_key, class: "form-control" %>
</p>

app/views/devices/_tracer.html.erb
Please enter your Guardian Mobility Tracer unit serial number (example: 0403A00010). If you have a common name
for the device, e.g. "Unit #5" you may optionally enter it here.

<p>
  <%= f.label "Name" %><br />
  <%= f.text_field :common_name, class: "form-control" %>
</p>

<p>
  <%= f.label "Serial number" %><br />
  <%= f.text_field :serial_number, class: "form-control" %>
</p>

app/views/devices/_watchdog.html.erb
Please enter the email address for your Faria VMS WatchDog unit. If you have a common name
for the device, e.g. "Unit #5" you may optionally enter it here.

<p>
  <%= f.label "Email Address" %><br />
  <%= f.text_field :serial_number, class: "form-control" %>
</p>

<p>
  <%= f.label "Name" %><br />
  <%= f.text_field :common_name, class: "form-control" %>
</p>

app/views/devices/edit.html.erb
<fieldset>

  <legend>Device Settings</legend>

  <%= form_for @device, {
      :loading => "Element.show('device_loading')",
      :complete => "Element.hide('device_loading')"
    } do |f| %>
    
    
    
    <%= render :partial => @device.device_type.name,
               :locals  => {:f => f}
               %>
               
    <p>
      <%= f.submit 'Update', class: "btn" %>
    </p>

    <% end %> 
 
</fieldset>

app/views/devices/index.html.erb
<fieldset>
  <legend>Tracking Devices</legend>
  <p>
    <button class="btn"><%= link_to 'Add new tracking device', new_device_path %></button>
  </p>
  <% if @devices.nil? %>
    <br />You have no tracking devices configured.
  <% else %>
      <table class="index sortable">
        <thead>
        <tr>
          <% if @loggedin_user.super? %>
              <th>Client</th>
          <% end %>
          <th>Type</th>
          <th>Name</th>
          <th>Serial Number</th>
          <th>Key</th>
        </tr>
        </thead>
        <tbody>
        <% @devices.each do |device| %>
            <tr bgcolor="<%= cycle("#dddddd", "ffffff") %>">
              <% if @loggedin_user.super? %>
                  <td><%= device.client.company_name %></td>
              <% end %>
              <td><%= h device.device_type.title %></td>
              <td><%= h device.common_name %></td>
              <%= %>
              <td><%= h device.serial_number %></td>
              <td><%= h device.request_key %></td>
              <td><%= link_to 'Edit', edit_device_path(device) %></td>
              <td><%= link_to 'Delete', device, :confirm => 'Are you sure you want to delete this tracking device?',
                              :method => :delete %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
  <% end %>
</fieldset>

app/views/devices/new.html.erb
<fieldset>

  <legend>New Tracking Device</legend>
  
<%= collection_select :device, :device_type_id, @device_types, :id, :title, {:prompt => "Select Type"}, {class: "form-control"} %>
<%= observe_field('device_device_type_id', :function => "
  $('device_forms').childElements().invoke('hide');
  $('device_' + value).show();
")%>

<div id="device_forms">

  <% @device_types.each do |device_type| %>

    <%= form_for @device, {
          :html => { :id => 'device_' + device_type.id.to_s,
                     :style => "display:none;" }
      } do |f| %>
      <br /><br />  
      
      <%= hidden_field_tag("device[device_type_id]", device_type.id) %>
      <%= render :partial => 'devices/' + device_type.name,
                 :locals  => {:f => f}
                 %>
      <%= f.submit 'Save' %>  
    <% end %>
    
  <% end %>
</div>

</fieldset>