config/routes.rb
#require 'subdomain'
Ddmap::Application.routes.draw do
  devise_for :users
  get 'job_viewer' => 'job_viewer#index', :as => :job_viewer
  resources :fishing_areas
  resources :staging_areas
  resources :custom_fields
  get 'staging_areas_company/:id.:format' => 'staging_areas#index' # :as => :staging_areas
  get 'marker/:name/:id.:format' => 'markers#show', :as => :markers
  get 'search/:controller/:name/:id.:format' => 'controller#search', :as => :search, :name => :name
  get 'wrrl_company_search/:id.:format' => 'wrrls#company_search', :as => :wrrl_company_search
  get 'wrrl_equipment_type_search/:id.:format' => 'wrrls#equipment_type_search', :as => :wrrls_search
  resources :staging_area_companies
  resources :staging_area_assets
  resources :public_maps
  resources :grp_plans
  resources :grp_areas
  resources :grps
  resources :grp_booms
  resources :grp_boom_types
  resources :devices
  post 'update_locations/:id' => 'devices#update_locations', :as => :update_devices
  resources :layers
  resources :stored_files
  resources :kmls
  resources :points
  resources :fishing_areas
  resources :area_categories

  #post 'ais_feeds/ais1' => 'aisFeeds#ais1'

  post '/public_maps/activate/:id' => 'public_maps#activate'

  resources :licenses
  resources :ships
  resources :fishing_vessels
  resources :fishing_trips
  resources :fishermen
  resources :privileges
  resources :faria_feeds
  resources :staging_area_feeds
  resources :clients
  resources :assets
  #resources :public_ships
  get 'my_ships.:format' => 'ships#index', :distill => 'my' #, :as => :my_ships, 
  get 'shared_ships.:format' => 'ships#index', :distill => 'shared' #, :as => :shared_ships, 
  get 'public_ships.:format' => 'ships#index', :distill => 'public' #, :as => :public_ships, 
  get 'my_ships/:id.:format' => 'assets#show' #, :as => :my_ships
  get 'shared_ships/:id.:format' => 'assets#show' #, :as => :shared_ships
  get 'public_ships/:id.:format' => 'assets#show' #, :as => :public_ships
  #get 'my_items.:format' => 'others#index', :as => :my_items, :distill => 'my'
  # get 'shared_items.:format' => 'others#index', :as => :shared_items, :distill => 'shared'
  # get 'public_items.:format' => 'others#index', :as => :public_items, :distill => 'public'
  # #get 'my_items/:id.:format' => 'assets#show', :as => :my_items
  # get 'shared_items/:id.:format' => 'assets#show', :as => :shared_items
  # get 'public_items/:id.:format' => 'assets#show', :as => :public_items
  resources :maps

  # get '/:controller(/:action(/:id))'
  #
  # post '/:controller(/:action(/:id))'


  #post '/ais_feeds/ais5', to: 'AisFeeds#ais5'

  post '/license/activate' => 'licenses#activate'

  root 'public#index'
  get '/' => 'public#index'

  %w(about products services contact success ).each do |page|
    get "/#{page}" => 'public#show', :page => page
  end
  get ':page' => 'private#show', :as => :private, :page => /map|help|admin/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
    attr_reader :password

    has_many :sessions, :dependent => :destroy
    has_many :logins, :dependent => :destroy
    has_many :licenses
    has_many :tags
    has_many :assets, :through => :tags
    
    has_and_belongs_to_many :layers, :join_table => :layers_users_privileges
    
    has_one :map, :dependent => :destroy
    
    belongs_to :client
    belongs_to :privilege
    
    # validates_presence_of :first_name, :last_name, :email
    #
    # validates_uniqueness_of :email, :message => 'is already in use by another user'
    #
    # validates_format_of :username, :with => /\A([a-z0-9_]{2,26})\z/i, :message => "must be 4 to 26 letters, numbers, or underscores and have no spaces"
    #
    # validates_format_of :password, :with => /\A([\x20-\x7E]){4,26}\z/,
    #                     :message => "must be 4 to 26 characters"
    #
    # validates_format_of :password, :with => /\A\S*\z/, :message => 'must not contain spaces'
    # validates_format_of :email, :with => /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i,
    #                     :message => "must be a valid email address."
    #
    #
    # validates_exclusion_of :username, :in => %w( support blog www billing help api ), :message => "The subdomain <strong>{{value}}</strong> is reserved and unavailable."
    #


    def super?
      false
    end

    def admin?
      false
    end
    
    def is?(user)
      self.id == user.id
    end
      
    def has_license?
      #licenses = License.find(:all, :conditions => "client_id = #{self.client.id}")
      licenses = License.where("client_id = :client", {client: self.client.id})
      licenses.any? {|license| !license.deactivated && (license.expires > Time.now)}
    end
    
    def account_active?
      self.client.active && self.active
    end
    
    def admin_for?(user)
      #  super users can admin all
      # admins can admin all with the same client_id
      # users can admin themselves only.
      self.super? || ((user.client_id == self.client_id) & self.admin?) || self.is?(user)
    end

    def self.find_by_username_and_password(username, password)
      user = self.find_by_username(username)
      if user and user.hashed_password == ENCRYPT.hexdigest(password + user.salt)
        return user
      end
    end

    # Devise handles this now
    # def temp_password
    #   #generate temp password for new users and resets, Only use 0-9 a-z A-Z
    #   Array.new(9) { [48+rand(10), 65+rand(26), 97+rand(26)][rand(3)].chr }.join
    # end
  
  private
  
    def scrub_username
      self.username.downcase!
    end

    def flush_passwords
      @password = @password_confirmation = nil
    end

    def password_is_not_being_updated?
      self.id and self.password.blank?
    end

end

# == Schema Information
#
# Table name: users
#
#  id              :integer         primary key
#  client_id       :integer
#  privilege_id    :integer
#  username        :string(255)
#  hashed_password :string(255)
#  salt            :string(255)
#  first_name      :string(255)
#  last_name       :string(255)
#  email           :string(255)
#  active          :boolean         default(TRUE)
#  eula            :boolean         default(FALSE)
#  last_login      :timestamp
#  created_at      :timestamp
#  updated_at      :timestamp
#  time_zone       :string(255)
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "private"
  # before_filter :ensure_login, :only => [:activate, :index, :new, :edit, :update, :create]
  # before_filter :ensure_logout, :only => []

  # AJAX POST /users/recover
  def recover
    @user = User.find_by_username(params[:username])

    respond_to do |format|
      if @user
        RecoveryMailer.sendRecovery(:key => Crypto.encrypt("#{@user.id}:#{@user.salt}"),
        :email => @user.email,
        :domain => request.env['HTTP_HOST']).deliver
        format.js { render :text =>  "Password reset. User will be emailed instructions." }
        format.html {
          flash[:notice] = "Password reset. User will be emailed instructions."
          redirect_to :back
        }
      else
        format.html{
          flash[:notice] = "Error: account could not be found."
          redirect_to :back
        }
      format.js { render :text =>  "Error: account could not be found." }

      end
    end
  end

  #~ # AJAX POST /users/activate
  def activate
    user = User.find(params[:id])

    if user.update_attribute(:active, !user.active)
      if user.active
        message = "This account is currently enabled."
      else
        message = "This account is currently disabled."     
      end
    else
      message = "Error: User account activation not changed"
    end

    respond_to do |format|
      format.js { render :text =>  message }
      format.html{
          flash[:notice] = message
          redirect_to :back
        }
    end
  end

  #~ # GET /users
  def index
    pub = Privilege.find_by_name('public')
    if @loggedin_user.super?
      # RAILS 3 @users = User.all(:order => "client_id, last_name", :conditions => ['privilege_id <> ?', pub.id])
      @users = User.joins(:client).where("privilege_id <> ?", pub.id).order('clients.company_name')
    elsif @loggedin_user.admin?
      # Can only list users with the same client
      # @users = User.find(:all, (rails 2 deprecated  finder)
      # :conditions => [ "client_id = ? AND privilege_id <> ?", @loggedin_user.client_id, pub.id ],
      # :order => "client_id, last_name")

      @users = User.where("client_id = ? AND privilege_id <> ?", @loggedin_user.client_id, pub.id)
                   .order(:client_id, :last_name)
    else 
      # standard users can't view user list
      error_404
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /users/new
  def new
    @user = User.new
    set_client_privilege
    @user.privilege_id = 3 # set the default privilege to "standard"
    # The layers allowed for the user defaults to the layers available to the admin
    # creating the user. If the loggedin_user is a super user, the layers
    # will update when the user updates the client menu.
    @layers = @loggedin_user.client.layers.all
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    if @loggedin_user.admin_for?(@user)
      set_client_privilege
      @layers = @user.client.layers.all.order('created_at DESC')
    else
      error_404
    end
  end

  # PUT /users/1
  def update
    @user = User.find(params[:id])
    set_client_privilege

    # If all checkboxes are unchecked, no params are sent.
    # To get around this we set a hidden param: layer_checkboxes.
    # If it is present and the checkbox values
    # are not, then we know to clear all of the layers.
    if params[:layer_checkboxes] && params[:user][:layer_ids].nil? 
      @user.remove_all_layers
    end

    respond_to do |format|
      # if the password was changed, make sure it matched in the confirmation field
      if params[:user][:password] && (params[:user][:password] != params[:user][:password_confirmation])
      	format.html {
          flash[:error] = 'Error: Make sure both fields match when changing password.'
          redirect_to :back 
        }
        format.js { render :text =>  "Error: Make sure both fields match when changing password." }
      # if the password was changed, check the size
      elsif params[:user][:password] && params[:user][:password].size < 6
      	format.html {
          flash[:error] = 'Error: Password must be at least 6 characters.'
          redirect_to :back 
        }
        format.js { render :text =>  "Error: Password must be at least 6 characters." }
      else
	    if @user.update_attributes!(params[:user])
	        format.html { 
	          flash[:notice] = 'User account was successfully updated.'
	          redirect_to :back
	        }
	        format.js { render :text =>  "User account successfully updated." }
	    else
	        format.html {
            flash[:error] = 'Error: User account was not successfully updated.'
	          redirect_to :back 
	        }
	        format.js { render :text =>  "Error: User account not updated." }
	      end
	    end
    end
  end

  # POST /users
  def create
    @user = User.new(params[:user])
    @pword = @user.temp_password
    @user.password = @pword
    if !@user.client_id
      @user.client_id = @loggedin_user.client_id
    end
    respond_to do |format|
      if @user.save
        # create a map for this user
        @map = Map.new(:user_id => @user.id)
        @map.save
        # Mailer.deliver_signup
        SignupMailer.signupMail(@user, @pword).deliver
        flash[:notice] = "Account for #{@user.first_name} #{@user.last_name} created. An invitation email was sent."
        format.html { redirect_to(:action => 'edit', :id => @user.id) }
      else
        set_client_privilege
        @layers = @user.client.layers.all(:order => :sort)
        format.html { render :action => "new" }
      end
    end
  end

  private

  def set_client_privilege
    if @loggedin_user.super?
      @clients = Client.all
      # RAILS 3 @privileges = Privilege.all(:order => "id DESC", :conditions => ['name <> (?)', 'public'])
      @privileges = Privilege.where('name <> :name', {name: 'public'}).order('id DESC')
    elsif @loggedin_user.admin?
      @privileges = Privilege.find(:all, :conditions => ["name NOT in (?)", ['super','public']])
      #Admins can't set anyone to be a super or public user.
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form-group">
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name, class: "form-control"%>
</div>
<div class="form-group">
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :email %><br />
  <%= f.text_field :email, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :username %> <br />
  <%= f.text_field :username, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :timezone%><br />
  <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {default: 'Pacific Time (US & Canada)'}, {:class => 'form-control'} %>
</div>

app/views/users/_layers.html.erb
Select layers this user may view:
<br />
<% @layers.each do |layer| -%>
  <% field_id = "layer_#{layer.id}" %>
  <br />
  <%= check_box_tag "user[layer_ids][]", layer.id, @user.layers.include?(layer), {:id => field_id} %>
  <%= label_tag field_id, h(layer.title) %>
<% end %>
<%= hidden_field_tag "layer_checkboxes", 1 %> 

app/views/users/edit.html.erb
<h1><%= @user.first_name + ' ' +  @user.last_name%></h1>

<ul data-tabs="tabs" class="nav nav-tabs" id="usertabs">  
  <li class="active" role="presentation"><a href="#account" data-toggle="tab">Account</a></li>  
  <li role="presentation"><a href="#layers" data-toggle="tab">Layers</a></li>  
</ul>

<div class="tab-content">
  <div class="tab-pane fade in active" id="account">
    <% if @privileges %>
      <% # If privileges are enabled, then this is an admin or super user.  %>

      <% if @loggedin_user.id != @user.id %>
        <% # Users can't deactivate their own accounts. Supers do other supers, admins, and users.  %>
        <% # Admins do other admins and users.  %>
            <h4>Administrator Options</h4>
      
        <%= button_to 'Enable/Disable Account', 
          :url => { :action => 'activate', :id => @user.id },
          :update => 'disable_message',
          :loading => "Element.show('active_loading')",
          :complete => "Element.hide('active_loading')"
        %>

        <% if @user.active %>
          <span id="disable_message">This account is currently enabled.</span>
        <% else %>
          <span id="disable_message">This account is currently disabled.</span>
        <% end %>
        
         <%= button_to "Recover Password", {action: "recover/#{@user.id}"}  %>
         A new password will be emailed to this user.
         <div id="reset_message"></div>
        
        <hr />
      <% end %>
    <% end %>
    
    <div <%= "style='float:left;margin-right:10px; border-right:thin solid grey;'" if @loggedin_user.is?(@user) %> >
      <%= form_for @user, {
          :update => "account_message",
          :loading => "Element.hide('account_message');Element.show('account_loading')",
          :complete => "Element.show('account_message');Element.hide('account_loading')",
          :class => "form"
          } do |f| -%>

        <% @user.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
          
        <% if @clients %>
          <p>
            <%= f.label :client %>
            <%= f.collection_select :client_id, @clients, :id, :company_name, {}, {class: "form-control"} %>
          </p>
        <% end %>
        
        <% if @privileges && !@loggedin_user.is?(@user) %>
          <p>
            <%= f.label :privilege %>
            <%= f.collection_select :privilege_id, @privileges, :id, :name, {}, {class: "form-control"} %>
          </p>

        <% end %>

        <%= render :partial => 'form' , :locals => {:f => f}%>
       
        <%= submit_tag "Submit", class: "btn" %>

        <div id="account_message"></div>
      <% end %>
    
  
    <div>

      <% # Reset password. Supers/admins can do an email reset for others. All can set their own password %>
          
      <% if @loggedin_user.is?(@user) %>

          <h3>Change Password</h3>
        
        <%= form_for @user do |f| %>
        
         <% @user.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
          
         <p>
           <label for="user_password">New Password:</label><br />
           <%= f.password_field :password, class: "form-control" %><br />
         </p>
         
         <p>
           <label for="user_password_confirmation">Password Confirmation:</label><br />
           <%= f.password_field :password_confirmation, class: "form-control" %><br />
         </p>
         
         <%= submit_tag "Submit", class: "btn" %>
      
       <% end %>  

      <% end %>

    </div>
  </div>

</div>
  <div class="tab-pane fade" id="layers">
   
    <%= form_for @user, {
    :loading => "Element.show('layer_loading')",
    :complete => "Element.hide('layer_loading')"
    } do |f| -%>

      <%= render :partial => 'layers' , :locals => {:f => f, :user => @user} %>
      <br />
      <%= f.hidden_field(:id) %>
      <br />
      <%= f.submit 'Update', class: "btn" %>
      <span id='layer_loading' class='loader' style='display:none;'>Updating...</span>
      
      <div id="layer_message"></div>

    <% end %>

  </div>
  
</div>

<script type="text/javascript">
  // Switch user in view when select element changes
  $('select#user_client_id').change(function () {
    var opt = $(this).val();
    document.location = '/users/' + opt + '/edit'
  });
</script>

app/views/users/index.html.erb
<fieldset>
  <legend>Users</legend>
  <p><button class="btn"><%= link_to 'Add new user', new_user_path %></button></p>
  <% if @users.length == 0 %>
    <br />You have no user accounts configured.
  <% else %>
      <table class="index sortable">
        <thead>
        <tr>
          <% if @loggedin_user.super? %>
              <th>Client</th>
          <% end %>
          <th>Privilege</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Email</th>
          <th>Active</th>
          <th>Last login</th>
      </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <tr bgcolor="<%= cycle("#dddddd", "#ffffff") %>">
              <% if @loggedin_user.super? %>
                  <td><%= h user.client.company_name %></td>
              <% end %>
              <td><%= h user.privilege.name %></td>
              <% if user.privilege.name== "public" %>
                  <td><%= h user.map.id %></td>
                  <td>--</td>
                  <td>--</td>
                  <td>--</td>
              <% else %>
                  <td><%= h user.username %></td>
                  <td><%= h user.first_name %></td>
                  <td><%= h user.last_name %></td>
                  <td><%= h user.email %></td>
              <% end %>
              <td><%= h user.active %></td>
              <td><%= h user.last_login %></td>
              <td><%= link_to 'Edit Account', edit_user_path(user) %></td>
              <td><%= link_to 'View Map', map_path(user.map) %></td>
            </tr>
        <% end %>
        </tbody>
  </table>
  <% end %>
</fieldset>

app/views/users/new.html.erb
<fieldset>
<legend>New User</legend>

<%= form_for(@user) do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>

	<% if @clients %>
		<p>
			<%= f.label :client %><br />
			<%= f.collection_select :client_id, @clients, :id, :company_name, {}, {class: "form-control"} %>
      <blockquote>Note: If the layers you select below are not enabled for this client, they'll
      be ignored for this user. To ensure the user's layers are correct, edit the user's
      settings after you've created the user here. (This situation only affects super users creating users for another client.)
      </blockquote>
    </p>
	<% end %>
	
	<% if @privileges %>
		<p>
			<%= f.label :privilege %><br />
			<%= f.collection_select :privilege_id, @privileges, :id, :name, {}, {class: "form-control"} %>
		</p>
	<% end %>

  <%= render :partial => 'form' , :locals => {:f => f} %>
  
  <div id="layers">
    <%= render :partial => 'layers' , :locals => {:f => f}%>
  </div>
  
  <p>
    <%= f.submit 'Create', class: "btn" %>
  </p>

<% end %>

</fieldset>