config/routes.rb
#require 'subdomain'
Ddmap::Application.routes.draw do
  devise_for :users
  get 'job_viewer' => 'job_viewer#index', :as => :job_viewer
  resources :fishing_areas
  resources :staging_areas
  resources :custom_fields
  get 'staging_areas_company/:id.:format' => 'staging_areas#index' # :as => :staging_areas
  get 'marker/:name/:id.:format' => 'markers#show', :as => :markers
  get 'search/:controller/:name/:id.:format' => 'controller#search', :as => :search, :name => :name
  get 'wrrl_company_search/:id.:format' => 'wrrls#company_search', :as => :wrrl_company_search
  get 'wrrl_equipment_type_search/:id.:format' => 'wrrls#equipment_type_search', :as => :wrrls_search
  resources :staging_area_companies
  resources :staging_area_assets
  resources :public_maps
  resources :grp_plans
  resources :grp_areas
  resources :grps
  resources :grp_booms
  resources :grp_boom_types
  resources :devices
  post 'update_locations/:id' => 'devices#update_locations', :as => :update_devices
  resources :layers
  resources :stored_files
  resources :kmls
  resources :points
  resources :fishing_areas
  resources :area_categories

  #post 'ais_feeds/ais1' => 'aisFeeds#ais1'

  post '/public_maps/activate/:id' => 'public_maps#activate'

  resources :licenses
  resources :ships
  resources :fishing_vessels
  resources :fishing_trips
  resources :fishermen
  resources :privileges
  resources :faria_feeds
  resources :staging_area_feeds
  resources :clients
  resources :assets
  #resources :public_ships
  get 'my_ships.:format' => 'ships#index', :distill => 'my' #, :as => :my_ships, 
  get 'shared_ships.:format' => 'ships#index', :distill => 'shared' #, :as => :shared_ships, 
  get 'public_ships.:format' => 'ships#index', :distill => 'public' #, :as => :public_ships, 
  get 'my_ships/:id.:format' => 'assets#show' #, :as => :my_ships
  get 'shared_ships/:id.:format' => 'assets#show' #, :as => :shared_ships
  get 'public_ships/:id.:format' => 'assets#show' #, :as => :public_ships
  #get 'my_items.:format' => 'others#index', :as => :my_items, :distill => 'my'
  # get 'shared_items.:format' => 'others#index', :as => :shared_items, :distill => 'shared'
  # get 'public_items.:format' => 'others#index', :as => :public_items, :distill => 'public'
  # #get 'my_items/:id.:format' => 'assets#show', :as => :my_items
  # get 'shared_items/:id.:format' => 'assets#show', :as => :shared_items
  # get 'public_items/:id.:format' => 'assets#show', :as => :public_items
  resources :maps

  # get '/:controller(/:action(/:id))'
  #
  # post '/:controller(/:action(/:id))'


  #post '/ais_feeds/ais5', to: 'AisFeeds#ais5'

  post '/license/activate' => 'licenses#activate'

  root 'public#index'
  get '/' => 'public#index'

  %w(about products services contact success ).each do |page|
    get "/#{page}" => 'public#show', :page => page
  end
  get ':page' => 'private#show', :as => :private, :page => /map|help|admin/

end

app/models/client.rb
# == Schema Information
# Schema version: 20100727173851
#
# Table name: clients
#
#  id            :integer         primary key
#  company_name  :string(255)
#  address1      :string(255)
#  address2      :string(255)
#  city          :string(255)
#  zip           :string(255)
#  company_url   :string(255)
#  contact_name  :string(255)
#  contact_phone :string(255)
#  contact_email :string(255)
#  contact_notes :text
#  active        :boolean         default(TRUE)
#  created_at    :timestamp
#  updated_at    :timestamp
#  state         :string(255)
#

class Client < ActiveRecord::Base
  
  has_many :users,          :dependent => :destroy
  has_many :users,          :through => :licenses
  has_many :licenses, -> {order :created_at}, :dependent => :destroy
  has_many :assets,         :dependent => :destroy
  has_many :shared_assets,  :dependent => :destroy
  # has_many :assets,         :through => :shared_assets
  has_many :devices,        :dependent => :destroy
  has_many :past_locations, :dependent => :destroy
  has_many :fishermen
  has_many :stored_files
    
  has_and_belongs_to_many :layers, :join_table => :clients_layers_privileges
  has_and_belongs_to_many :clients, :join_table => :client_share_privileges, :association_foreign_key => 'recipient_id', :foreign_key => 'sharer_id'

  validates_presence_of :company_name
   
  validates_format_of :contact_email, :with => /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i,
                      :message => "must be a valid email address"
  
  def remove_all_layers
    connection.delete("DELETE FROM clients_layers_privileges WHERE client_id = #{id}")
  end

  def remove_all_clients
    connection.delete("DELETE FROM client_share_privileges WHERE sharer_id = #{id}")
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  layout "private" 


  # GET /clients
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /clients/new
  def new
    @client = Client.new
    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
    @license = License.new
    @layers = Layer.all.order('created_at DESC')
    @clients = Client.where('id <> :id', {id: @client.id})
  end

  # POST /clients
  def create
    @client = Client.new(user_params)
    
    respond_to do |format|
      if @client.save
        
        #Every client gets a public map user with a map
        priv = Privilege.find_by_name('public')
        uniq = ([Array.new(9){rand(256).chr}.join].pack('m').chomp[1..8] + Time.now.to_f.to_s).gsub('.','_')
        pw = [Array.new(9){rand(256).chr}.join].pack('m').chomp
        user = User.create(
          :client => @client,
          :privilege => priv,
          :username => uniq,
          :first_name => 'Public Map',
          :last_name => 'User',
          :email => "#{uniq}@foobar.com",
          :password => pw,
          :password_confirmation => pw,
          :eula => true)
        Map.create(:user => user)
        
        flash[:notice] = 'Client was successfully created. 
                          Make sure to set up licenses, layers, and an admin user.'
        format.html { redirect_to(:action => 'edit', :id => @client.id) }
      else
        flash[:notice] = 'Error creating client.'
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /clients/1
  def update
    @client = Client.find(params[:id])

    # if all checkboxes are unchecked, no params are sent.
    # to get around this we set hidden params: layer_checkboxes and
    # shared_checkboxes. If they're present and the checkbox values
    # are not, then we know to clear all of the layers/clients.
    if params[:layer_checkboxes]
      @client.remove_all_layers if params[:client][:layer_ids].nil? # layer permissions
    end
    if params[:sharing_checkboxes]
      @client.remove_all_clients if params[:client].nil? # sharing with other clients
    end

   respond_to do |format|
     if @client.update_attributes(user_params)
        format.html { 
          flash[:notice] = 'Company account successfully updated.'
          redirect_to :action => "edit" 
        }
        format.js { render :text =>  "Client account successfully updated." }
      else
        format.html { render :action => "edit" }
        format.js { render :text =>  "Error. Client account not updated." }
      end
    end
  end

private

def user_params
  params.require(:client).permit(:active, :company_name, :address1, :address2, :city, :zip, :company_url, :contact_name, :contact_phone, :contact_email, :contact_notes, layer_ids: [], client_ids: [])
end

end

app/helpers/clients_helper.rb
module ClientsHelper


end

app/views/clients/_account.html.erb
<div class="col-md-4" style="float:left; padding-right:20px;">
  <p>
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name, class: "form-control" %>
  </p>
  <p>
    <%= f.label :address1 %><br />
    <%= f.text_field :address1, class: "form-control" %>
  </p>
  <p>
    <%= f.label :address2 %><br />
    <%= f.text_field :address2, class: "form-control" %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city, class: "form-control" %>
  </p>
  <p>
    <%= f.label :zip %><br />
    <%= f.text_field :zip, class: "form-control" %>
  </p>
  <p>
    <%= f.label :company_url %><br />
    <%= f.text_field :company_url, class: "form-control" %>
  </p>
  <p>
    <%= f.label :contact_name %><br />
    <%= f.text_field :contact_name, class: "form-control" %>
  </p>
  <p>
    <%= f.label :contact_phone %><br />
    <%= f.text_field :contact_phone, class: "form-control" %>
  </p>
  <p>
    <%= f.label :contact_email %><br />
    <%= f.text_field :contact_email, class: "form-control" %>
  </p>
  <p>
    <%= f.submit 'Submit', class: "btn" %>
  </p>
</div>

<div class="col-md-3">
  <p>
    <%= f.label :contact_notes %><br />
    <%= f.text_area :contact_notes, class: "form-control" %>
  </p>
</div>

app/views/clients/_licenses.html.erb
<table class="index">
  <tr>
    <th>Expires</th>
    <th>Created By</th>
    <th>Active</th>
  </tr>
      
  <% for license in client.licenses %>
  
  <tr bgcolor="<%= cycle("#dddddd", "#ffffff") %>">
    <td width="100"><%= license.expires.strftime('%b %d %Y') %></td>
    <td><%= license.user.first_name + ' ' + license.user.last_name%></td>
      <td width="200" align="right">

        <% if license.deactivated? %>
          <span id="msg_<%= license.id %>">no</span>
        <% else %>
          <span id="msg_<%= license.id %>">yes</span>
        <% end %>

        <% button_to "Dis/enable",
                     :url => {:controller => "licenses", :action => "activate", :id => license.id},
                     :update => 'msg_' + license.id.to_s,
                     :loading => "Element.show('load_" + license.id.to_s + "')",
                     :complete => "Element.hide('load_" + license.id.to_s + "')"
        %>
        <%= button_to "Disable/Enable", {:action => "activate", :controller => "licenses", :id => license.id.to_s}, {:form_class => "licenseForm", :remote => false, class: "", data: {confirm: 'Are you sure?', disable_with: 'loading...'}} %>

               
      </td>
    </tr>
  <% end %>
</table>
<br /><br />

app/views/clients/edit.html.erb
<h1><%= @client.company_name %></h1>

<br />

<ul data-tabs="tabs" id="clienttabs" class="nav nav-tabs">  
  <li class="active" role="presentation"><a href="#account_tab" data-toggle="tab">Account</a></li>  
  <li role="presentation"><a href="#license_tab" data-toggle="tab">Licenses</a></li>
  <li role="presentation"><a href="#layer_tab" data-toggle="tab">Layers</a></li>  
  <li role="presentation"><a href="#sharing_tab" data-toggle="tab">Sharing</a></li>  
</ul>

<div class="tab-content">
  <div class="tab-pane fade in active" id="account_tab">

    <%= form_for(@client) do |f| %>
       <% @client.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>

       <p>
         <%= f.check_box :active %><label for="client_Account Active.">Account Active?</label>
       </p>

       <%= render :partial => 'account',
                 :locals  => {:client => @client, 
                              :f => f 
                              }
       %>
    <% end %>

  </div>

  <div class="tab-pane fade" id="license_tab">
   
    <div id="licenses">
      <% if @client.licenses.length > 0 %>
        <%= render :partial => 'licenses',
                   :locals  => {:client => @client, 
                                :licenses => @client.licenses
        } %>
      <% end %>
    </div>
    
    <b>Add a license for this client</b>
    
    <p style="color: red"><%= flash[:error] %></p>

    <%= form_for [@client, @license], url:licenses_path do |f| -%>
        <%= hidden_field_tag('client_id', @client.id) %>
        Expires: <%= f.date_select :expires, {}, {} %>
        <%= f.submit 'Add', class: "btn" %>
    <% end %>  

  </div>

  <div class="tab-pane fade" id="layer_tab">

    Select layers this client will have access to.<br />

    <%= form_for @client, {} do |f| -%>
      <% @layers.each do |layer| -%>
        <% field_id = "layer_#{layer.id}" %>
        <br />
        <%= check_box_tag "client[layer_ids][]", layer.id, @client.layers.include?(layer), {:id => field_id} %>
        <%= label_tag field_id, h(layer.title) %>
      <% end %>
      <br />
      <%= hidden_field_tag "layer_checkboxes", 1 %>
      <%= f.submit 'Update', class: "btn" %>
    <% end %>

  </div>

  <div class="tab-pane fade" id="sharing_tab">

  	Select the clients this client may share assets with.<br />

    <%= form_for @client, {} do |f| -%>
      <% @clients.each do |client| -%>
        <% field_id = "client_#{client.id}" %>
        <br />
        <%= check_box_tag "client[client_ids][]", client.id, @client.clients.include?(client), {:id => field_id} %>
        <%= label_tag field_id, h(client.company_name) %>
      <% end %>
      <br />
      <%= hidden_field_tag "sharing_checkboxes", 1 %>
      <%= f.submit 'Update', class: "btn" %>
    <% end %>

  </div>
</div>

app/views/clients/index.html.erb
<fieldset>
  <legend>Clients</legend>
  <p>
    <button class="btn"><%= link_to 'Add new client', new_client_path %></button>
  </p>
  <% if @clients.nil? %>
    <br />You have no clients configured.
  <% else %>
      <table class="index sortable">
        <thead>
        <tr>
          <th>Company</th>
          <th>Contact</th>
          <th>Active</th>
        </tr>
        </thead>
        <tbody>
        <% @clients.each do |client| %>
            <tr bgcolor="<%= cycle("#dddddd", "#ffffff") %>">
              <td>
                <b><%= h client.company_name %></b><br/>
                <%= h client.address1 %><br/>
                <%= h client.address2 %>
                <% if client.address2.to_s.length != 0 %><br/>
                <% end %>
                <%= h client.city %>, <%= h client.state %> <%= h client.zip %><br/>
                <%= h client.company_url %>
              </td>
              <td>
                <%= h client.contact_name %><br/>
                <%= h client.contact_phone %><br/>
                <%= h client.contact_email %>
              </td>
              <td><%= h client.active %></td>
              <td><%= link_to 'Edit', edit_client_path(client) %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
  <% end %>
</fieldset>

app/views/clients/new.html.erb
<fieldset>

  <legend>New Client</legend>

  <%= form_for(@client) do |f| %>

    <% @client.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>

    <%= render :partial => 'account',
               :locals  => {:client => @client, 
                            :f => f 
                            }
     %>


  <% end %>

</fieldset>