config/routes.rb
#require 'subdomain'
Ddmap::Application.routes.draw do
  devise_for :users
  get 'job_viewer' => 'job_viewer#index', :as => :job_viewer
  resources :fishing_areas
  resources :staging_areas
  resources :custom_fields
  get 'staging_areas_company/:id.:format' => 'staging_areas#index' # :as => :staging_areas
  get 'marker/:name/:id.:format' => 'markers#show', :as => :markers
  get 'search/:controller/:name/:id.:format' => 'controller#search', :as => :search, :name => :name
  get 'wrrl_company_search/:id.:format' => 'wrrls#company_search', :as => :wrrl_company_search
  get 'wrrl_equipment_type_search/:id.:format' => 'wrrls#equipment_type_search', :as => :wrrls_search
  resources :staging_area_companies
  resources :staging_area_assets
  resources :public_maps
  resources :grp_plans
  resources :grp_areas
  resources :grps
  resources :grp_booms
  resources :grp_boom_types
  resources :devices
  post 'update_locations/:id' => 'devices#update_locations', :as => :update_devices
  resources :layers
  resources :stored_files
  resources :kmls
  resources :points
  resources :fishing_areas
  resources :area_categories

  #post 'ais_feeds/ais1' => 'aisFeeds#ais1'

  post '/public_maps/activate/:id' => 'public_maps#activate'

  resources :licenses
  resources :ships
  resources :fishing_vessels
  resources :fishing_trips
  resources :fishermen
  resources :privileges
  resources :faria_feeds
  resources :staging_area_feeds
  resources :clients
  resources :assets
  #resources :public_ships
  get 'my_ships.:format' => 'ships#index', :distill => 'my' #, :as => :my_ships, 
  get 'shared_ships.:format' => 'ships#index', :distill => 'shared' #, :as => :shared_ships, 
  get 'public_ships.:format' => 'ships#index', :distill => 'public' #, :as => :public_ships, 
  get 'my_ships/:id.:format' => 'assets#show' #, :as => :my_ships
  get 'shared_ships/:id.:format' => 'assets#show' #, :as => :shared_ships
  get 'public_ships/:id.:format' => 'assets#show' #, :as => :public_ships
  #get 'my_items.:format' => 'others#index', :as => :my_items, :distill => 'my'
  # get 'shared_items.:format' => 'others#index', :as => :shared_items, :distill => 'shared'
  # get 'public_items.:format' => 'others#index', :as => :public_items, :distill => 'public'
  # #get 'my_items/:id.:format' => 'assets#show', :as => :my_items
  # get 'shared_items/:id.:format' => 'assets#show', :as => :shared_items
  # get 'public_items/:id.:format' => 'assets#show', :as => :public_items
  resources :maps

  # get '/:controller(/:action(/:id))'
  #
  # post '/:controller(/:action(/:id))'


  #post '/ais_feeds/ais5', to: 'AisFeeds#ais5'

  post '/license/activate' => 'licenses#activate'

  root 'public#index'
  get '/' => 'public#index'

  %w(about products services contact success ).each do |page|
    get "/#{page}" => 'public#show', :page => page
  end
  get ':page' => 'private#show', :as => :private, :page => /map|help|admin/

end

app/models/asset.rb
# == Schema Information
# Schema version: 20100727173851
#
# Table name: assets
#
#  id                  :integer         primary key
#  asset_type_id       :integer
#  current_location_id :integer
#  client_id           :integer
#  visibility_id       :integer
#  is_active           :boolean         default(TRUE)
#  common_name         :string(255)
#  created_at          :timestamp
#  updated_at          :timestamp
#

class Asset < ActiveRecord::Base

  belongs_to :asset_type
  belongs_to :client
  belongs_to :visibility
  belongs_to :current_location, :dependent => :destroy

  has_many :past_locations, :dependent => :destroy
  has_many :custom_fields, :dependent => :destroy
  has_many :devices, :through => :tethers
  has_many :tethers, :dependent => :destroy
  has_many :routes, :dependent => :destroy
  has_many :images
  has_many :users, :through => :tags
  has_many :shared_assets
  has_many :clients, :through => :shared_assets

  has_one :tag, :dependent => :destroy
  has_one :ship, :dependent => :destroy
  has_one :other, :dependent => :destroy
  has_one :aircraft, :dependent => :destroy
  has_one :fishing_vessel, :dependent => :destroy

  validates_presence_of :common_name

  def constitute
    # Return an object that will be shown in a balloon for this type of asset.
    case self.asset_type.name
      when "ship"
        # ship_detail = self.ship
        # binding.pry
        # ship_detail['name'] = self.common_name
        # ship_detail['owner'] = self.client.company_name if self.client != nil
        # ship_detail['icon'] = self.ship.icon
        # ship_detail['age'] = age(self.current_location.timestamp) + ' ago'
        # ship_detail

        ship_detail = {}
        self.ship.attributes.each do |key, item|
          ship_detail[key] = item
        end
        ship_detail['name'] = self.common_name
        ship_detail['owner'] = self.client.company_name if self.client != nil
        ship_detail['icon'] = self.ship.icon
        ship_detail['age'] = age(self.current_location.timestamp) + ' ago'
        ship_detail

      when "fishing_vessel"
        #Boat info
        ship_detail = self.fishing_vessel
        ship_detail['name'] = self.common_name
        ship_detail['owner'] = self.client.company_name
        ship_detail['icon'] = self.fishing_vessel.icon
        # Current trip information
        trip = self.fishing_vessel.current_trip
        ship_detail['trip'] = trip
        ship_detail['crew'] = trip.fishermen.all.map {|m| m.first_name + " " + m.last_name + " - " + m.duties}
        ship_detail['gear'] = trip.fishing_gear.all.map {|g| g.title}
        ship_detail['intended'] = trip.intended_catches.all.map {|c| c.fish.title}
        ship_detail['actual'] = trip.intended_catches.all.map {|c| c.fish.title + ": " + (3000+100*(1+rand(100))).to_s}
        ship_detail
      when "other"
        other_detail = self.other
        other_detail['lat'] = self.current_location.lat.to_s
        other_detail['lon'] = self.current_location.lon.to_s
        other_detail['name'] = self.common_name
        other_detail['timestamp'] = Time.zone.parse(self.current_location.timestamp.to_s).strftime('%r %b %d, %Y')
        custom_data = self.custom_fields
        if !custom_data.empty?
          details = {}
          custom_data.each do |detail|
            details[detail.name] = detail.value
          end
        end
        other_detail['details'] = details
        other_detail
    end
  end 

  private

  def age(time)
    age_seconds = Time.zone.now - time
    parts = Array.new
    factors = [['day', 86400],['hr', 3600],['min',60],['sec',1]]
    age = factors.inject(age_seconds) do |memo, factor|
      unit, amount = factor
      value, in_seconds = memo.divmod(amount)
      parts << "#{value} #{unit}" if value != 0
      memo -= value * amount
    end

    parts.join(', ')
  end

end

app/models/asset_type.rb
# == Schema Information
# Schema version: 20100727173851
#
# Table name: asset_types
#
#  id    :integer         primary key
#  name  :string(255)
#  title :text
#  sort  :integer
#

class AssetType < ActiveRecord::Base
  has_many :assets
  has_many :icons
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  layout 'private'
  before_filter :ensure_login
  
  # GET /assets
  # GET /assets.xml
  def index
    if @loggedin_user.super?
      # public ships have a client_id = NULL
      # RAILS 3 @assets = Asset.find(:all, :conditions => ['client_id IS NOT NULL'], :order => :client_id)
      @assets = Asset.where('client_id IS NOT NULL').order('client_id DESC')
     elsif @loggedin_user.admin?
      # Can only list users with the same client
       @assets = Asset.where(:client_id => @loggedin_user.client_id)
    else 
      # standard users can't view assets list
      error_404
    end  
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @assets }
    end
  end

  # GET /assets/1
  def show
    @asset = Asset.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb     
      format.xml  { render :xml => @asset }
      format.json  { render :json => @asset.constitute.to_json}
    end
  end
  
  # GET /assets/new
  # GET /assets/new.xml
  def new
    @asset = Asset.new
    @visibilities = Visibility.all
    @asset_types = AssetType.all.order('id DESC')
    if @loggedin_user.super?
      @clients = Client.all
    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
    @client = @asset.client
    @custom_field = CustomField.new
    @icons = Icon.where(:asset_type_id => @asset.asset_type_id)
    @visibilities = Visibility.all
    @device = Device.new
    @device_types = DeviceType.all
    if @asset.asset_type.name == 'fishing_vessel'
      @fishing_trip = FishingTrip.new
      # @fishing_trips = FishingTrip.find_all_by_fishing_vessel_id(
      #   @asset.fishing_vessel.id, :order=>"created_at DESC",
      #   :include => [:fishermen, :fish, :real_fish, :fishing_gear]
      # )
      @fishing_trips = FishingTrip.includes([:fishermen, :fish, :real_fish, :fishing_gear]).
          where(:fishing_vessel_id => @asset.fishing_vessel.id).
          order('created_at DESC')
      @fishing_gear = FishingGear.all
      @fish = Fish.all
      @fishermen = @asset.client.fishermen.all.order(:last_name)
    end
  end

  # POST /assets
  def create
    @asset = Asset.new(params[:asset])

    @asset.client_id ||= @loggedin_user.client_id
    
    respond_to do |format|
      if @asset.save
        case @asset.asset_type.name
          when 'ship'
            @ship = Ship.create(:asset_id => @asset.id)
          when 'aircraft'
            @aircraft = Aircraft.create(:asset_id => @asset.id) 
          when 'fishing_vessel'
            @fishing_vessel = FishingVessel.create(:asset_id => @asset.id)
          when 'other'
            @other = Other.create(:asset_id => @asset.id)
          else
        end
        flash[:notice] = 'Asset was successfully created.'
        format.html { redirect_to(edit_asset_path(@asset)) }
      else
        flash[:notice] = 'Error: Asset was not created.'
        format.html { redirect_to :back }
      end
    end
  end
  
  # PUT /assets/1
  # PUT /assets/1.xml
  def update
    @asset = Asset.find(params[:id])

    # if all checkboxes are unchecked, no params are sent.
    # to get around this we set a hidden param: device_checkboxes.
    # If it's present and the checkbox values
    # are not, then we know to clear all of the tethers.
    if params[:device_checkboxes]
      Tether.delete_all(:asset_id => @asset.id) if params[:asset].nil?
    end
    if params[:sharing_checkboxes]
      SharedAsset.delete_all(:asset_id => @asset.id) if params[:asset].nil?
    end
    
    respond_to do |format|
      if @asset.update_attributes!(params[:asset])
        format.html { 
          flash[:notice] = 'Asset was successfully updated.'
          redirect_to :back
        }
        format.xml  { head :ok }
        format.js {render :text => "Asset information updated."}
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
        format.js {render :Text => "Error: Asset information not updated."}
        end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.xml
  def destroy
    @asset = Asset.find(params[:id])
    if @asset.destroy
      flash[:notice] = 'Asset was deleted.'

      respond_to do |format|
        format.html { redirect_to(assets_url) }
        format.xml  { head :ok }
      end
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper

end

app/views/assets/_devices.html.erb
<% if @client.devices.length == 0 %>

  <br />You have no tracking devices configured.

<% else %>

  Select a device to track this asset.
  <br /><br />
  
  <%= form_for @asset, {
            :loading => "Element.show('device_loading')",
            :complete => "Element.hide('device_loading')"
        } do |f| %>
    <% for device in @client.devices %>
      <% field_id = "d_#{device.id}" %>
      <%= check_box_tag "asset[device_ids][]", device.id, @asset.devices.include?(device), :id => field_id %>
      <%= label_tag field_id, h(device.common_name.to_s  + ' ' + device.device_type.title.to_s + ' ' + device.serial_number.to_s) %>
      <br/>
    <% end %>
    <%= hidden_field_tag "device_checkboxes", 1 %>
    <%= f.submit 'Update', class: "btn" %>
  <% end %>

<% end %>
 
<hr />


<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:error] %>
  </div>
<% end %>
Add new device:

<%= collection_select :device, :device_type_id, @device_types, :id, :title, {:prompt => 'Select Type'}, {class: 'form-control'} %>

  <div id="device_forms">
  
    <% @device_types.each do |device_type| %>

      <%= form_for @device, {
            :update => 'devices',
            :loading => "Element.show('device_saving')",
            :complete => "Element.hide('device_saving')",
            :html => { :id => 'device_' + device_type.id.to_s,
                       :style => "display:none;" }
        } do |f| %>
        <br /><br />  
        <%= hidden_field_tag("device[device_type_id]", device_type.id) %>
        <%= hidden_field_tag("device[asset_ids]", @asset.id) %>
        <%= render :partial => 'devices/' + device_type.name,
                   :locals  => {:f => f}
                   %>
        <%= f.submit 'Save', class: "btn" %>
      <% end %>
      
    <% end %>
  </div>

app/views/assets/_fields.html.erb
If you would like to display extra data for this asset, enter it here.

<br /><br />

<table>
  <tr>
    <th width="240"><b>Name</b></th>
    <th width="240"><b>Value</b></th>
  </tr>
</table>
  
<% for field in @asset.custom_fields %>
  <%= form_for(field, :method => :put) do |f| -%>
  <div id='d<%= field.id %>'>
    <table style="display:block">
      <tr>
        <td width="240"><%= field.name %></td>
        <td width="240"><%= field.value %></td>
        <td>
          <%= button_to_function "Edit", "$('d#{field.id}').childElements().invoke('toggle')"%>
          
        </td>
      </tr>
    </table>
    
    <div style="display:none">     
      
        
          <% field.id %>
        <table>
          <tr>
            <td width="240"><%= f.text_field :name, :value => field.name %></td>
            <td width="240"><%= f.text_field :value, :value => field.value %></td>
        
            <td>
              <%= button_to_function "Cancel", "$('d#{field.id}').childElements().invoke('toggle')"%>
              <%= f.submit 'Save' %>
               <% end %>
            </td>
            <td>
            <%= form_for(field, :method => :delete) do |f| %>
              <% field.id %>
              <%= f.submit 'Delete' %>
            <% end %>

            </td>
          </tr>
        </table>
     
    </div>
  </div>
<% end %>

<p style="color: red"><%= flash[:error] %></p>  

      <%= form_for(@custom_field) do |f| -%>
        <%= fields_for @asset do |c| %>
          <%= c.hidden_field('id', :value => @asset.id) %>
        <% end %>
  <table>
    <tr>
      <td width="240">
        <%= f.text_field :name, class: "form-control" %>
      </td>
      <td width="240">
        <%= f.text_field :value, class: "form-control" %>
      </td>
      <td>
        <%= f.submit 'Add', class: "btn" %>
      </td>
    </tr>
  </table>
<% end %> 

app/views/assets/_fishing_trip.html.erb
<fieldset>

  <legend>New Fishing Trip</legend>

  <%= form_for @fishing_trip, {
      :update => "trip_data",
      :loading => "Element.show('trip_loading')",
      :complete => "Element.hide('trip_loading')"
      } do |t| -%>

  <%= fields_for @asset.fishing_vessel do |f| %>

  <div style="float:left; margin-right:20px;">
      <%= f.hidden_field :id %>
    <p>    
      <%= t.label :date_submitted %><br />
      <%= t.text_field :date_submitted %>
      <%#= calendar_date_select_tag "fishing_trip[date_submitted]", "", :popup => :force %>
    </p>  

    <p>    
      <%= t.label :date_certified %><br />
      <%= t.text_field :date_certified %>
      <%#= calendar_date_select_tag "fishing_trip[date_certified]", "", :popup => :force %>
    </p>  
    
    <p>    
      <%= t.label :confirmation, "Confirmation code" %><br />
      <%= t.text_field :confirmation%>
    </p>
      
    Intended catch:
    
    <% @fish.each do |fish| -%>
      <% field_id = "fish#{fish.id}" %>
      <br />
      <%= check_box_tag "fishing_trip[fish_ids][]", fish.id, false, {:id => field_id} %>
      <%= label_tag field_id, h(fish.title) %>
    <% end %>
    <%= hidden_field_tag "fish_checkboxes", 1 %>
    
  </div>
  
  <div style="float:left; margin-right:20px;">
    
    Gear:
    
    <% @fishing_gear.each do |gear| -%>
      <% field_id = "gear#{gear.id}" %>
      <br />
      <%= check_box_tag "fishing_trip[fishing_gear_ids][]", gear.id, false, {:id => field_id} %>
      <%= label_tag field_id, h(gear.title) %>
    <% end %>
    <%= hidden_field_tag "gear_checkboxes", 1 %>
    
  </div>
  
  <div style="float:left; margin-right:20px;">

    Crew:
    
    <% @fishermen.each do |hand| -%>
      <% field_id = "hand#{hand.id}" %>
      <br />
      <%= check_box_tag "fishing_trip[fisherman_ids][]", hand.id, false, {:id => field_id} %>
      <%= label_tag field_id, hand.first_name + ", " + hand.last_name + " - " + hand.duties %>
    <% end %>
    <%= hidden_field_tag "fishermen_checkboxes", 1 %>
  
  </div>
  
  <p style="clear:both;">
    <%= t.submit 'Create' %>
  </p>
  
  <% end %>

<% end %>

</fieldset>

<%= render :partial => "fishing_trips/list", :locals => {:fishing_trips => @fishing_trips} %>

app/views/assets/_fishing_vessel.html.erb
<% form_for @asset.fishing_vessel, {
      :loading => "Element.show('ship_loading')",
      :complete => "Element.hide('ship_loading')"
      } do |f| -%>

  

  <div style="float:left; margin-right:20px;">
  
    <p>    
      <%= f.label :icon_id, "Vessel type" %><br />
      <%= f.collection_select :icon_id, @icons, :id, :name %>
    </p>
    
    <p>
      <%= f.label :draught %><br />
      <%= f.text_field :draught%>
    </p>

    <p>
      <%= f.label :length, "Ship length"%><br />
      <%= f.text_field :length %>
    </p>

    <p>
      <%= f.label :width, "Ship width"%><br />
      <%= f.text_field :width %>
    </p>
    
    <p>
      <%= f.label :vms_number, "VMS number" %><br />
      <%= f.text_field :vms_number%>
    </p>
    
    <p>
      <%= f.label :vms_passcode, "VMS passcode" %><br />
      <%= f.text_field :vms_passcode%>
    </p>
    
    <p>
      <%= f.label :vms_email, "VMS email" %><br />
      <%= f.text_field :vms_email%>
    </p>    
    
  </div>
  
  <div>
  
    <p>
      <%= f.label :call_sign %><br />
      <%= f.text_field :call_sign%>
    </p>
    
    <p>
      <%= f.label :phone_number %><br />
      <%= f.text_field :phone%>
    </p>
    
    <p>
      <%= f.label :home_port %><br />
      <%= f.text_field :port%>
    </p>
    
  </div>
  
  <p style="clear:both;">
    <%= f.submit 'Update' %>
  </p>
  
<% end %>

app/views/assets/_ship.html.erb
This information is optional. Providing the distance from your GPS unit to the edges of your ship will locate it more accurately on the map. Draught will displayed if set. The ship type will determine the icon used for the ship.

<% remote_form_for @asset.ship, {
      :loading => "Element.show('ship_loading')",
      :complete => "Element.hide('ship_loading')"
      } do |f| -%>

  <%= f.error_messages %>

  <p>    
    <%= f.label :Ship_Type %><br />
    <%= f.collection_select :icon_id, @icons, :id, :name, {}, {class: "form-control"} %>
  </p>

  <p>
  <%= f.label :draught %><br />
  <%= f.text_field :draught, class: "form-control" %>
  </p>

<div id="dims">
  <div>
  
    <p>
    <%= f.label :Distance_To_Bow %><br />
    <%= f.text_field :dim_bow, class: "form-control" %>
      <%= link_to_function("Don't know position of tracking device?", "$('dims').childElements().invoke('toggle')") %>
    </p>

    <p>
    <%= f.label :Distance_To_Stern %><br />
    <%= f.text_field :dim_stern, class: "form-control" %>
    </p>

    <p>
    <%= f.label :Distance_to_Starboard %><br />
    <%= f.text_field :dim_starboard, class: "form-control" %>
    </p>

    <p>
    <%= f.label :Distance_to_port%><br />
    <%= f.text_field :dim_port, class: "form-control" %>
    </p>

  </div>

  <div id="2dims" style="display:none;">

    <p>
    <%= f.label :Ship_Length %><br />
    <%= f.text_field :length, class: "form-control" %>
      <%= link_to_function("Set device distance to ship edges.", "$('dims').childElements().invoke('toggle')") %>
    </p>

    <p>
    <%= f.label :Ship_Width %><br />
    <%= f.text_field :width, class: "form-control" %>
    </p>

  </div>
</div>

<p>
  <%= f.submit 'Update', class: "btn" %>

<% end %>

app/views/assets/edit.html.erb
<h1><%= @asset.common_name %></h1>

<ul data-tabs="tabs" class="nav nav-tabs" id="usertabs">  
  <li class="active" role="presentation"><a href="#asset_tab" data-toggle="tab">Settings</a></li>  
  <li role="presentation"><a href="#devices" data-toggle="tab">Tracking</a></li>
  <li role="presentation"><a href="#sharing" data-toggle="tab">Sharing</a></li>  
  <li role="presentation"><a href="fields" data-toggle=="tab">Data Fields</a></li>
  <% if @asset.asset_type.name == 'ship' %>
    <li role="presentation"><a href="#ship_data" data-toggle="tab">Ship Specs</a></li>
  <% end %> 
  <% if @asset.asset_type.name == 'fishing_vessel' %>
    <li role="presentation"><a href="#ship_data" data-toggle="tab">Ship Specs</a></li>
    <li role="presentation"><a href="#trip_data" data-toggle="tab">Trips</a></li>
  <% end %> 
  <% if @asset.asset_type.name == 'aircraft' %>
    <li role="presentation"><a href="#aircraft_data" data-toggle="tab">Aircraft Specs</a></li>
  <% end %> 
</ul>

<div class="tab-content">
  <div class="tab-pane fade in active" id="asset_tab">

    <%= form_for @asset do |f| -%>
         
      <p>
        <%= f.label :Name %><br />
        <%= f.text_field :common_name, class: "form-control" %>
      </p>
      
      <p>
        <%= f.label :visibility %>
        <% @visibilities.each do |v| %>
          <br />
          <%= f.radio_button :visibility_id, v.id %>
          <%= v.name %> - <%= v.description %>
        <% end %>
      </p>
      
      <p>
        <%= f.check_box :is_active %>
        <%= f.label :Active %> - Asset will be tracked and displayed according to visibility settings.
      </p>
        
      <p>
        <%= f.submit 'Update', class: "btn" %>
      </p>
      
    <% end %>

  </div>

  <div class="tab-pane fade" id="devices">
    <%= render :partial => 'devices',
               :locals  => {:asset => @asset, 
                            :devices => @devices
                            } %>
  </div>

  <div class="tab-pane fade" id="sharing">

    <% if @client.clients.length == 0 %>
      
      You do not have client sharing enabled. Please contact us to share assets with other clients.
      
    <% else %>
      
      Share this asset with:<br />

      <%= form_for @asset, {
            } do |f| -%>
        <% @client.clients.each do |client| -%>
          <br />
          <% field_id = "client_#{client.id}" %> 
          <%= check_box_tag "asset[client_ids][]", client.id, @asset.clients.include?(client), {:id => field_id} %>
          <%= label_tag field_id, h(client.company_name) %>
          
          <% if @asset.asset_type.name == "fishing_vessel" %>
            (
            <%= check_box_tag "", client.id, rand(2)==1, {:id => field_id + "L"} %>
            <%= label_tag field_id + "L", "Hide Location"%>
            
            <%= check_box_tag "", client.id, rand(2)==1, {:id => field_id + "C"} %>
            <%= label_tag field_id + "C", "Hide Catch" %>
            
            <%= check_box_tag "", client.id, rand(2)==1, {:id => field_id + "I"} %>
            <%= label_tag field_id + "I", "Show Inspection Log" %>
            )
            
            <br />
            
          <% end %>
          
        <% end %>
        <br />
        <%= hidden_field_tag "sharing_checkboxes", 1 %>
        <%= f.submit 'Update', class: "btn" %>
      <% end %>
    
    <% end %>
    
  </div>

  <% if @asset.asset_type.name == 'ship' %>

    <div id="ship_data">
      <%= render :partial => 'ship',
                 :locals  => {:asset => @asset, 
                              :icons => @icons
                             } %>
    </div>
    
  <% elsif @asset.asset_type.name == 'fishing_vessel' %>

    <div class="tab-pane fade" id="ship_data">
      <%= render :partial => 'fishing_vessel',
                 :locals  => {:asset => @asset, 
                              :icons => @icons
                             } %>
    </div>
    
    <div class="tab-pane fade" id="trip_data">
      <%= render :partial => 'fishing_trip',
                 :locals  => {:asset => @asset,
                              :fish => @fish,
                              :fishing_gear => @fishing_gear,
                              :fishermen => @fishermen
                  }
      %>
    </div>
      
  <% elsif @asset.asset_type.name == 'aircraft' %>

    <div class="tab-pane fade" id="aircraft_data">
      <%= render :partial => 'aircraft',
                 :locals  => {:asset => @asset, 
                              :icons => @icons
                             } %>
    </div>
    
  <% end %>

  <div class="tab-pane fade" id="fields">
    <%= render :partial => 'fields',
               :locals  => {:asset => @asset, 
                            :custom_field => @custom_field
                           } %>
  </div>
</div>

app/views/assets/index.html.erb
<fieldset>
  <legend>Assets</legend>
  <p>
    <button class="btn"><%= link_to 'Add new asset', new_asset_path %></button>
  </p>
  <% if @assets.count == 0 %>
    <br />You have no assets configured.
  <% else %>
      <table class="index sortable">
        <thead>
        <tr>
          <% if @loggedin_user.super? %>
              <th>Client</th>
          <% end %>
          <th>Name</th>
          <th>Active</th>
        </tr>
        </thead>
        <tbody>
        <% @assets.each do |asset| %>
            <tr bgcolor="<%= cycle("#dddddd", "#ffffff") %>">
              <% if @loggedin_user.super? %>
                  <td><%= asset.client.company_name %></td>
              <% end %>
              <td><%= asset.common_name %></td>
              <td><%= asset.is_active %></td>
              <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
              <td><%= link_to 'Delete', asset, :confirm => 'Are you sure? All related data will be deleted.', :method => :delete %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
  <% end %>
</fieldset>

app/views/assets/new.html.erb
<fieldset>
  <legend>New Asset</legend>

  <%= form_for(@asset) do |f| %>
    
    
    <% if @clients #super users only%>
      <p>
        <%= f.label :client %><br />
        <%= f.collection_select :client_id, @clients, :id, :company_name, {}, {class: "form-control"} %>
      </p>
    <% end %>
    
    <p>
      <%= f.label :asset_name %><br />
      <%= f.text_field :common_name, class: "form-control" %>
    </p>
    
    <p>
      <%= f.label :asset_type %><br />
      <%= f.collection_select :asset_type_id, @asset_types, :id, :title, {}, {class: "form-control"} %>
    </p>

    <p>
      <%= f.submit 'Create', class: "btn" %>
    </p>
    
  <% end %>

</fieldset>